name: null
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- variantbam=1.4.4a=hc088bd4_4
- _libgcc_mutex=0.1=main
- bzip2=1.0.8=h7b6447c_0
- ca-certificates=2020.10.14=0
- certifi=2020.6.20=pyhd3eb1b0_3
- libedit=3.1.20191231=h14c3975_1
- libffi=3.3=he6710b0_2
- libgcc-ng=9.1.0=hdf63c60_0
- libstdcxx-ng=9.1.0=hdf63c60_0
- ncurses=6.2=he6710b0_1
- pip=19.3.1=py27_0
- python=2.7.18=h15b4118_1
- readline=8.0=h7b6447c_0
- setuptools=44.0.0=py27_0
- sqlite=3.33.0=h62c20be_0
- tk=8.6.10=hbc83047_0
- wheel=0.35.1=py_0
- xz=5.2.5=h7b6447c_0
- zlib=1.2.11=h7b6447c_3
prefix: /scicore/home/egliadr/GROUP/projects/COVID-19/Illumina/Softwares/snakemake/build/envs/mock_env/variantbam

